name: Build Android APK with Buildozer
on:
  push:
    branches: [ maestro ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Build APK with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        workdir: Contadores-master
        buildozer_version: stable

    - name: Upload and save the generated APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: Flex-Rex-App
        path: ${{ steps.buildozer.outputs.filename }}
